### ISSUE TITLE
目前存在问题

### ISSUE THREAD

**Issue by hhmlyg1966** [tokyohost/shopping-teamOne#13]
1. 每项订单之总额与此订单之订单项小计之总和不一致
2. 添加订单时，必须更新相关产品之数量，相关用户之余额，积分与折扣
3. 添加到购物车时，显示折扣一项，小计金额时考虑折扣

**Comment by hhmlyg1966** [comment]
用随机码方法，能显示每订单编号下的各订单项吗？

**Comment by tokyohost** [comment]
问题一正在debug，目前设计是用随机码作为每个订单唯一识别码，并绑定订单项表中每一项对应，确保不会重复

**Comment by hhmlyg1966** [comment]
好的

**Comment by hhmlyg1966** [comment]
问题之二，可以考虑在后台用触发器完成

**Comment by hhmlyg1966** [comment]
李雪辉，我如何将完成的内容上传到我在此处的分支中，作为你们的一个版本？

**Comment by tokyohost** [comment]
首先您需要在项目目录中执行：
`git remote add origin https://github.com/tokyohost/shopping-teamOne.git`
来关联github的远程库
在本地新建一个分支：
`git branch 分支名字`
使用：
`git checkout 分支名字`
切换到新建立的分支
然后使用：
`git status  `
查看文件变动记录
使用：
`git add 文件名`
将想要提交的内容文件添加到暂存区中等待提交
使用：
`git commit -m ”此处写提交版本简介“ `
来创建一次提交,
最后使用：
`git push origin 分支名字`
来完成提交

**Comment by hhmlyg1966** [comment]
谢谢你！

**Comment by hhmlyg1966** [comment]
李雪辉，我想发到我的根库（master）中。

**Comment by tokyohost** [comment]
你应该重新创建一个库然后使用 
`git remote -v `
查看当前关联的远程库
`git remote remove origin/远程库名字 `
来移除当前关联的远程库
然后通过
`git remote add origin   你自己的git存储库链接`
来重新关联属于你自己的远程库
最后开始进行push操作

```
git add .
git commit -m 'push信息'
git push origin master
```
一般不直接提交  master主分支，因为主分支会直接修改存储库的代码

**Comment by hhmlyg1966** [comment]
好的，谢谢你！

**Comment by tokyohost** [comment]
所有问题已基本解决
